# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69d783968be4b676cedf9efe6eaaca1d94f91bbfdf9f58c96ee9889d674a24489d96ada90879f5c0592ff452f76f83717cb8ce0d8ebe0efa174636adfafe9fe

test:
  secret_key_base: 2f8b8ae1d39ca84d7535caee84f32595d964770670ffc858d3d535d182b74f9139d312e47f4402b3bfd7c501250bedd39e080434d4fc555c2edb40bd13b86368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
